# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramMVVM3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for InstagramMVVM3
	pod 'JGProgressHUD'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'SDWebImage'
	pod 'YPImagePicker'
end
